/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class exportarBD extends javax.swing.JDialog {

    /**
     * Creates new form exportarBD
     */
    public exportarBD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExportar = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        textRuta = new javax.swing.JTextField();
        botonExportar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botonSeleccionar = new javax.swing.JButton();
        iconBD = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelExportar.setBackground(new java.awt.Color(40, 41, 41));
        panelExportar.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 102, 102)));

        labelTitulo.setBackground(new java.awt.Color(40, 41, 41));
        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Exportar Base de Datos");
        labelTitulo.setMaximumSize(new java.awt.Dimension(111, 23));
        labelTitulo.setMinimumSize(new java.awt.Dimension(111, 23));
        labelTitulo.setOpaque(true);
        labelTitulo.setPreferredSize(new java.awt.Dimension(111, 23));

        textRuta.setEditable(false);
        textRuta.setBackground(new java.awt.Color(40, 41, 41));
        textRuta.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        textRuta.setForeground(new java.awt.Color(255, 255, 255));
        textRuta.setBorder(null);
        textRuta.setCaretColor(new java.awt.Color(255, 255, 255));

        botonExportar.setBackground(new java.awt.Color(29, 184, 83));
        botonExportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonExportar.setForeground(new java.awt.Color(255, 255, 255));
        botonExportar.setText("Exportar");
        botonExportar.setBorder(null);
        botonExportar.setFocusPainted(false);
        botonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportar(evt);
            }
        });

        botonSeleccionar.setBackground(new java.awt.Color(29, 184, 83));
        botonSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setText("Seleccionar Carpeta");
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionar(evt);
            }
        });

        iconBD.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        iconBD.setForeground(new java.awt.Color(255, 255, 255));
        iconBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/database  (4).png"))); // NOI18N

        botonAtras.setBackground(new java.awt.Color(29, 184, 83));
        botonAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras(evt);
            }
        });

        javax.swing.GroupLayout panelExportarLayout = new javax.swing.GroupLayout(panelExportar);
        panelExportar.setLayout(panelExportarLayout);
        panelExportarLayout.setHorizontalGroup(
            panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSeleccionar)
                    .addGroup(panelExportarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconBD, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonAtras))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(panelExportarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelExportarLayout.setVerticalGroup(
            panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarLayout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionar)
                    .addComponent(textRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExportarLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(botonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAtras))
                    .addComponent(iconBD, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionar
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int se = fc.showSaveDialog(null);
        if(se == JFileChooser.APPROVE_OPTION){
            String ruta = fc.getSelectedFile().getPath();
            textRuta.setText(ruta);
        }
    }//GEN-LAST:event_botonSeleccionar

    private void exportar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportar
        // TODO add your handling code here:
        String ruta = textRuta.getText();
        String name = "\\backup.sql";
        String backus = "";
        if(ruta.trim().length()!=0){
            try{
                backus = "C:\\xampp\\mysql\\bin\\mysqldump --opt -u"+Conexion.getuser()+" -p"+Conexion.getpassword()+" -B "+Conexion.getdb()+" -r "+ruta+name;
                Runtime rt = Runtime.getRuntime();
                rt.exec(backus);
                ImageIcon ua = new ImageIcon("src/img/success.png");
                JOptionPane.showMessageDialog(null, "Backup creado: "+ruta, "Mensaje", JOptionPane.OK_OPTION, ua);
                dispose();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_exportar

    private void atras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_atras

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exportarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exportarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exportarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exportarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                exportarBD dialog = new exportarBD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonExportar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JLabel iconBD;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelExportar;
    private javax.swing.JTextField textRuta;
    // End of variables declaration//GEN-END:variables
}
